# Use root/example as user/password credentials

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example

    # (this is just an example, not intended to be a production configuration)
